########################################################################################################################
## Common Config
########################################################################################################################
service.conf:
  tamll-config-location: "classpath:config/tmall-sqlmap-config.xml"
  tmall-mapper-location: "classpath:com/elevenst/terroir/product/registration/**/mapper/*.xml"
logging:
  config: "classpath:logback-spring.xml"
spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: local
tomcat:
  ajp:
    port: 9988
    protocol: AJP/1.3
    secure: false
    allow-trace: true
    scheme: http
    enable: true
server:
  ssl:
    enabled: false

## Common Properties
common:
  upload:
    url: http://i.011st.com
    path: /data1/upload
img:
  upload:
    domain: http://image.11st.co.kr
soffice:
  url: http://soffice.11st.co.kr


---
########################################################################################################################
## Localhost
########################################################################################################################
spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles: local
eleven:
  tmall:
    url: "jdbc:oracle:thin:@10.40.30.245:10101:TMALL"
    username: "tmall"
    password: "tmall#stg1"
    driver-class-name: "oracle.jdbc.OracleDriver"
    initial-size: 5
    test-on-borrow: true
    validation-query: "select 1 from dual"
    max-idle: 10
    min-idle: 1
    max-active: 10
logging:
  level:
    org.springframework.transaction.interceptor: "TRACE"

## Common properties
product:
  file:
    upload-path: "/data1/upload/st"
    temp-path: "/data1/upload/st/temp/prd"
    gift-path: "/data1/upload/st/gift"
milab:
  category:
    svr:
      url: "http://172.28.4.65:4090"
esocache:
  enable: true
  cache_ttl: 3600
  zookeeper:
    host: 172.18.176.65:2181,172.18.176.66:2181,172.18.176.67:2181
    path: /ESOCache
    timeout: 10000
  clusters: farm1
  pool:
    con:
      timeout: 1000
      max: 50
    idle:
      max: 5
      min: 2
common:
  upload:
    url: http://image.11st.co.kr

img:
  upload:
    server:
      path: /data1/upload/dev
---
########################################################################################################################
## Staging
########################################################################################################################
spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles: stage
eleven:
  tmall:
    url: "jdbc:oracle:thin:@172.18.176.69:1525:TMALL"
    username: "tmall"
    password: "tmall#stg1"
    driver-class-name: "oracle.jdbc.OracleDriver"
    initial-size: 5
    test-on-borrow: true
    validation-query: "select 1 from dual"
    max-idle: 10
    min-idle: 1
    max-active: 10

## Common properties
product:
  file:
    upload-path: "/data1/upload/st"
    temp-path: "/data1/upload/st/temp/prd"
    gift-path: "/data1/upload/st/gift"
milab:
  category:
    svr:
      url: "http://172.28.4.65:4090"
esocache:
  enable: true
  cache_ttl: 3600
  zookeeper:
    host: 172.18.176.65:2181,172.18.176.66:2181,172.18.176.67:2181
    path: /ESOCache
    timeout: 10000
  clusters: farm1
  pool:
    con:
      timeout: 1000
      max: 50
    idle:
      max: 5
      min: 2

common:
  upload:
    url: http://image.11st.co.kr

img:
  upload:
    server:
      path: /data1/upload/st
---
########################################################################################################################
## Production
########################################################################################################################
spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles: real
eleven:
  tmall:
    url: "jdbc:oracle:thin:@(description=(address_list=(address=(host=172.18.185.79)(protocol=tcp)(port=1527))(address=(host=172.18.185.146)(protocol=tcp)(port=1527))(address=(host=172.18.185.150)(protocol=tcp)(port=1527))(load_balance=off)(failover=on))(connect_data=(SERVER=DEDICATED)(service_name= TMALL)))"
    username: "tmall"
    password: "tmall#ved1"
    driver-class-name: "oracle.jdbc.OracleDriver"
    initial-size: 5
    test-on-borrow: true
    validation-query: "select 1 from dual"
    max-idle: 10
    min-idle: 1
    max-active: 10

## Common properties
product:
  file:
    upload-path: "/data1/upload"
    temp-path: "/data1/upload/temp/prd"
    gift-path: "/data1/upload/gift"
milab:
  category:
    svr:
      url: "http://172.28.4.65:4090"
esocache:
  enable: true
  cache_ttl: 3600
  zookeeper:
    host: 172.18.187.123:2181,172.18.187.124:2181,172.18.187.125:2181
    path: /ESOCache
    timeout: 10000
  clusters: farm1
  pool:
    con:
      timeout: 1000
      max: 50
    idle:
      max: 10
      min: 5

common:
  upload:
    url: http://image.11st.co.kr

img:
  upload:
    server:
      path: /data1/upload/